name: Build and Test Python Package

on:
  push:
    tags:
      - '*'
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build pytest
      - name: Build package
        run: python -m build
      - name: Run tests
        run: |
          pip install .
          pytest
      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')  # Alleen uitvoeren bij een nieuwe tag
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.whl
            dist/*.tar.gz
          generate_release_notes: true